# e.g openjdk-11-jre, openjdk-11-jdk

- name: Install open jdk
  apt:
    name: "openjdk-{{jdk_version}}-{{jdk_distribution}}"
    update_cache: yes

- name: ubuntu set soft link
  shell: |
     rm -f /usr/lib/jvm/java-1*
     ln -sf /usr/lib/jvm/java-*/jre /usr/lib/jvm/
     ln -sf /usr/lib/jvm/java-* /usr/lib/jvm/java
     ln -sf /usr/lib/jvm/java /usr/
#     ln -sf /usr/bin/java /usr/lib/jvm/java/
