# e.g openjdk-11-jre, openjdk-11-jdk

- name: Install open jdk
  apt:
    name: "openjdk-{{jdk_version}}-{{jdk_distribution}}"
    update_cache: yes

- name: ubantu set soft link
  shell: ln -sf /usr/lib/jvm/java-*/jre /usr/lib/jvm/
