#1 install JDK by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

#2 Configure
- name: Setting JRE Securerandom
  lineinfile:
    path: /usr/lib/jvm/jre/lib/security/java.security
    regexp: 'securerandom.source=file:/dev/random'
    line: 'securerandom.source=file:/dev/./urandom'

## set environment variable
- block:
  - name: Copy jdk_env to /etc/profile.d
    template:
      src: jdk_env.sh
      dest: '/etc/profile.d'
      mode: 0640

  - name: Export JAVA_HOME environment variable for this shell
    shell: export JAVA_HOME=/usr/lib/jvm/java

# debug
- name: Set JAVA environment variable
  shell: echo $JAVA_HOME
  register: java_env

- name: check JAVA_HOME
  debug:
    var: java_env.stdout
  
# Check version
- name: Check JAVA Version
  shell: sudo sh -c "java -version 2>> /data/logs/install_version.txt"
