- import_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: Debian.yml
  when: ansible_os_family == 'Debian' 

- name: Check JAVA Version
  shell: java -version
  register: java_ver
  notify: java Version