#1 install JDK by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

#2 Configure
- name: Setting JRE Securerandom
  lineinfile:
    path: /usr/lib/jvm/jre/lib/security/java.security
    regexp: 'securerandom.source=file:/dev/random'
    line: 'securerandom.source=file:/dev/./urandom'

- name: Upload JAVA environment settings script
  template:
    src: env.sh
    dest: '/tmp'
    mode: 0750
    
- name: Install JAVA environment settings script
  shell: bash env.sh
  args:
    chdir: /tmp

# debug
- name: Set JAVA environment variable
  shell: echo $JAVA_HOME
  register: java_env

- name: check JAVA_HOME
  debug:
    var: java_env.stdout
  
  
# Check version
- name: Check JAVA Version
  shell: sudo sh -c "java -version 2>> /data/logs/install_version.txt"
