#1 install JDK by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

#2 Configure
- name: Setting JRE Securerandom
  lineinfile:
    path: /usr/lib/jvm/jre/lib/security/java.security
    regexp: 'securerandom.source=file:/dev/random'
    line: 'securerandom.source=file:/dev/./urandom'

- name: Set JAVA environment variable
  shell: |
    echo "export JAVA_HOME=/usr/lib/jvm/java" >> /etc/profile
    echo "export PATH=\$JAVA_HOME/bin:\$PATH" >> /etc/profile
    source /etc/profile
    
- name: Set JAVA environment variable
  shell: echo $JAVA_HOME
  register: java_env

- name: check JAVA_HOME
  debug:
    var: java_env.stdout
  
  
# Check version
- name: Check JAVA Version
  shell: sudo sh -c "java -version 2>> /data/logs/install_version.txt"
