- set_fact:
    yum_name: "{{jdk_meta[jdk_version].yum_name}}"

- debug:
    msg: Installing {{yum_name}} 
    
- name: Install openjdk
  yum:
    name: "{{yum_name}}"
    state: present

# AmazonLinux JDK11版本以及一上版本
- name: Install openjdk
  yum:
    name: "java-{{jdk_version}}"
  when: jdk_version > '8' and  ansible_distribution == 'Amazon'
