- set_fact:
    yum_name: "{{jdk_meta[jdk_version][jdk_distribution].yum_name}}"
    when: ansible_distribution != 'Amazon'

- set_fact:
    yum_name: "{{jdk_meta[jdk_version][jdk_distribution].yum_name_aws}}"
    when: ansible_distribution == 'Amazon'
    
- debug:
    msg: Installing {{yum_name}} 
    
- name: Install openjdk on {{ansible_distribution}}
  yum:
    name: "{{yum_name}}"
    state: present
