- set_fact:
    yum_name: "{{jdk_meta_redhat[jdk_version][jdk_distribution].yum_name}}"
  when: ansible_distribution != 'Amazon'

- set_fact:
    yum_name: "{{jdk_meta_redhat[jdk_version][jdk_distribution].yum_name_aws}}"
  when: ansible_distribution == 'Amazon'
    
- debug:
    msg: Installing {{yum_name}} 
    
- name: Install openjdk on {{ansible_distribution}}
  yum:
    name: "{{yum_name}}"
    state: present

- name: Set soft link for Java
  shell: |
     ln -sf /usr/lib/jvm/java-* /usr/lib/jvm/java
     ln -sf /usr/lib/jvm/java /usr/
